version: '3.8'

services:
  db:
    image: postgres:15
    container_name: wearedev_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wearedev_net

volumes:
  postgres_data:

networks:
  wearedev_net:
    driver: bridge 